export const ORDER_CREATE_REQUEST ='ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS ='ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAILURE ='ORDER_CREATE_FAILURE'

export const ORDER_DETAILS_REQUEST ='ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS ='ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAILURE ='ORDER_DETAILS_FAILURE'

export const ORDER_PAY_REQUEST ='ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS ='ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAILURE ='ORDER_PAY_FAILURE'
export const ORDER_PAY_RESET ='ORDER_PAY_RESET'

export const ORDER_MERCHANT_CREDIT_REQUEST ='ORDER_MERCHANT_CREDIT_REQUEST'
export const ORDER_MERCHANT_CREDIT_SUCCESS ='ORDER_MERCHANT_CREDIT_SUCCESS'
export const ORDER_MERCHANT_CREDIT_FAILURE ='ORDER_MERCHANT_CREDIT_FAILURE'
export const ORDER_MERCHANT_CREDIT_RESET ='ORDER_MERCHANT_CREDIT_RESET'


export const ORDER_INSUFFICIENT_REQUEST ='ORDER_INSUFFICIENT_REQUEST'
export const ORDER_INSUFFICIENT_SUCCESS ='ORDER_INSUFFICIENT_SUCCESS'
export const ORDER_INSUFFICIENT_FAILURE ='ORDER_INSUFFICIENT_FAILURE'
export const ORDER_INSUFFICIENT_RESET ='ORDER_INSUFFICIENT_RESET'

export const ORDER_APPROVE_REQUEST ='ORDER_APPROVE_REQUEST'
export const ORDER_APPROVE_SUCCESS ='ORDER_APPROVE_SUCCESS'
export const ORDER_APPROVE_FAILURE ='ORDER_APPROVE_FAILURE'

export const ORDER_LIST_MY_REQUEST ='ORDER_LIST_MY_REQUEST'
export const ORDER_LIST_MY_SUCCESS ='ORDER_LIST_MY_SUCCESS'
export const ORDER_LIST_MY_FAILURE ='ORDER_LIST_MY_FAILURE'
export const ORDER_LIST_MY_RESET ='ORDER_LIST_MY_RESET'

export const ORDER_LIST_REQUEST ='ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS ='ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAILURE ='ORDER_LIST_FAILURE'


export const UNPAID_ORDER_LIST_REQUEST ='UNPAID_ORDER_LIST_REQUEST'
export const UNPAID_ORDER_LIST_SUCCESS ='UNPAID_ORDER_LIST_SUCCESS'
export const UNPAID_ORDER_LIST_FAILURE ='UNPAID_ORDER_LIST_FAILURE'

export const ORDER_DELIVER_REQUEST ='ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS ='ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAILURE ='ORDER_DELIVER_FAILURE'
export const ORDER_DELIVER_RESET ='ORDER_DELIVER_RESET'
